name: "Build - Check & Clippy"
on:
  push:
    branches:
      - master
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache
  PROJECT_NAME: obmc

jobs:
  check:
    name: "Build - check"
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            task: format
            run: cargo fmt --all --check
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            task: check
            run: cargo check --all --locked
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            task: clippy
            run: cargo clippy --all-targets --all-features --locked -- -D warnings
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            task: check
            run: cargo check --all --locked
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            task: clippy
            run: cargo clippy --all-targets --all-features --locked -- -D warnings
    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    steps:
      - uses: actions/checkout@v4
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
      - name: Setup Rust toolchain
        shell: bash
        run: |
          rustup toolchain install
          rustup target add "${{ matrix.target }}" 2>/dev/null || true
          rustup show
      - name: Install cargo tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall,cargo-make,just,taplo

      - name: ${{ matrix.task }}
        run: ${{ matrix.run }}

  clippy:
    name: "Build - clippy"
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    steps:
      - uses: actions/checkout@v4
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
      - name: Setup Rust toolchain
        shell: bash
        run: |
          rustup toolchain install
          rustup target add "${{ matrix.target }}" 2>/dev/null || true
          rustup show
      - name: Install cargo tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall,cargo-make,just,taplo

      - name: Run Cargo fmt
        run: cargo fmt --all --check

      - name: Run Clippy with pedantic
        run: cargo clippy --all-targets --all-features --locked -- -W clippy::pedantic

      - name: Build project
        run: cargo build --release --locked --all
